### PR TITLE
Fixed the issue that a number in secret could be found multiple times

### PR DESCRIPTION
**Pull request by nonchris**
Already found positions are now blocked.

There are still some edge case when numbers occure multiple times in secret - the counter of half right numbers could be decreased altough it would be right if a number was guesses at the right and wrong spot.
There is also the problem that the `.find()` method wont locate a second value at a later position if a first one is found in the string.

### CODE REVIEW

**Comment by Knniff** [comment]
The changed code doesn´t show the found but wrongly placed numbers.

**Comment by nonchris** [comment]
It does, did you try it?

**Comment by Knniff** [comment]
Now it works, i tested it before but maybe i didnt copy everthing.

**Comment by nonchris** [comment]
Okay, never mind 😄

**Pull request merged**
